/**
 * Города России для выбора в виджете погоды (OpenWeatherMap).
 * value: "CityName,ru" для API
 */
export const RUSSIAN_CITIES = [
  { value: 'Moscow,ru', label: 'Москва' },
  { value: 'Saint Petersburg,ru', label: 'Санкт-Петербург' },
  { value: 'Novosibirsk,ru', label: 'Новосибирск' },
  { value: 'Yekaterinburg,ru', label: 'Екатеринбург' },
  { value: 'Kazan,ru', label: 'Казань' },
  { value: 'Nizhny Novgorod,ru', label: 'Нижний Новгород' },
  { value: 'Chelyabinsk,ru', label: 'Челябинск' },
  { value: 'Samara,ru', label: 'Самара' },
  { value: 'Rostov-on-Don,ru', label: 'Ростов-на-Дону' },
  { value: 'Ufa,ru', label: 'Уфа' },
  { value: 'Krasnoyarsk,ru', label: 'Красноярск' },
  { value: 'Voronezh,ru', label: 'Воронеж' },
  { value: 'Perm,ru', label: 'Пермь' },
  { value: 'Volgograd,ru', label: 'Волгоград' },
  { value: 'Krasnodar,ru', label: 'Краснодар' },
  { value: 'Saratov,ru', label: 'Саратов' },
  { value: 'Tyumen,ru', label: 'Тюмень' },
  { value: 'Tolyatti,ru', label: 'Тольятти' },
  { value: 'Izhevsk,ru', label: 'Ижевск' },
  { value: 'Barnaul,ru', label: 'Барнаул' },
  { value: 'Ulyanovsk,ru', label: 'Ульяновск' },
  { value: 'Irkutsk,ru', label: 'Иркутск' },
  { value: 'Khabarovsk,ru', label: 'Хабаровск' },
  { value: 'Yaroslavl,ru', label: 'Ярославль' },
  { value: 'Vladivostok,ru', label: 'Владивосток' },
  { value: 'Makhachkala,ru', label: 'Махачкала' },
  { value: 'Tomsk,ru', label: 'Томск' },
  { value: 'Orenburg,ru', label: 'Оренбург' },
  { value: 'Kemerovo,ru', label: 'Кемерово' },
  { value: 'Novokuznetsk,ru', label: 'Новокузнецк' },
  { value: 'Ryazan,ru', label: 'Рязань' },
  { value: 'Astrakhan,ru', label: 'Астрахань' },
  { value: 'Naberezhnye Chelny,ru', label: 'Набережные Челны' },
  { value: 'Penza,ru', label: 'Пенза' },
  { value: 'Lipetsk,ru', label: 'Липецк' },
  { value: 'Tula,ru', label: 'Тула' },
  { value: 'Kursk,ru', label: 'Курск' },
  { value: 'Sochi,ru', label: 'Сочи' },
  { value: 'Stavropol,ru', label: 'Ставрополь' },
  { value: 'Ulan-Ude,ru', label: 'Улан-Удэ' },
  { value: 'Tver,ru', label: 'Тверь' },
  { value: 'Magnitogorsk,ru', label: 'Магнитогорск' },
  { value: 'Ivanovo,ru', label: 'Иваново' },
  { value: 'Bryansk,ru', label: 'Брянск' },
  { value: 'Belgorod,ru', label: 'Белгород' },
  { value: 'Surgut,ru', label: 'Сургут' },
  { value: 'Vladimir,ru', label: 'Владимир' },
  { value: 'Nizhnevartovsk,ru', label: 'Нижневартовск' },
  { value: 'Chita,ru', label: 'Чита' },
  { value: 'Kaliningrad,ru', label: 'Калининград' },
  { value: 'Arkhangelsk,ru', label: 'Архангельск' },
  { value: 'Smolensk,ru', label: 'Смоленск' },
  { value: 'Volzhsky,ru', label: 'Волжский' },
  { value: 'Murmansk,ru', label: 'Мурманск' },
  { value: 'Saransk,ru', label: 'Саранск' },
  { value: 'Cherepovets,ru', label: 'Череповец' },
  { value: 'Vologda,ru', label: 'Вологда' },
  { value: 'Vladikavkaz,ru', label: 'Владикавказ' },
  { value: 'Tambov,ru', label: 'Тамбов' },
  { value: 'Grozny,ru', label: 'Грозный' },
  { value: 'Kostroma,ru', label: 'Кострома' },
  { value: 'Petrozavodsk,ru', label: 'Петрозаводск' },
  { value: 'Yoshkar-Ola,ru', label: 'Йошкар-Ола' },
  { value: 'Sterlitamak,ru', label: 'Стерлитамак' },
  { value: 'Taganrog,ru', label: 'Таганрог' },
  { value: 'Bratsk,ru', label: 'Братск' },
  { value: 'Dzerzhinsk,ru', label: 'Дзержинск' },
  { value: 'Orsk,ru', label: 'Орск' },
  { value: 'Angarsk,ru', label: 'Ангарск' },
  { value: 'Blagoveshchensk,ru', label: 'Благовещенск' },
  { value: 'Yakutsk,ru', label: 'Якутск' },
  { value: 'Nalchik,ru', label: 'Нальчик' },
  { value: 'Maykop,ru', label: 'Майкоп' },
  { value: 'Elista,ru', label: 'Элиста' },
  { value: 'Abakan,ru', label: 'Абакан' },
  { value: 'Gorno-Altaysk,ru', label: 'Горно-Алтайск' },
  { value: 'Simferopol,ru', label: 'Симферополь' },
  { value: 'Sevastopol,ru', label: 'Севастополь' },
] as const

export const DEFAULT_CITY_VALUE = 'Kursk,ru'

export function getCityLabel(value: string): string {
  const found = RUSSIAN_CITIES.find((c) => c.value === value)
  return found ? found.label : value.split(',')[0]
}
